<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Liz Anderson">

<title>CapDAP Final Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Anderson_FinalReport_CapDAP_files/libs/clipboard/clipboard.min.js"></script>
<script src="Anderson_FinalReport_CapDAP_files/libs/quarto-html/quarto.js"></script>
<script src="Anderson_FinalReport_CapDAP_files/libs/quarto-html/popper.min.js"></script>
<script src="Anderson_FinalReport_CapDAP_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Anderson_FinalReport_CapDAP_files/libs/quarto-html/anchor.min.js"></script>
<link href="Anderson_FinalReport_CapDAP_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Anderson_FinalReport_CapDAP_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Anderson_FinalReport_CapDAP_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Anderson_FinalReport_CapDAP_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Anderson_FinalReport_CapDAP_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CapDAP Final Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Liz Anderson </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="final-report" class="level1">
<h1><span class="smallcaps"><u>Final Report</u></span></h1>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This data was collected by Edward Faison and David Foster as part of the Harvard Forest Long-Term Ecological Research Project, and for a masters thesis written by Edward Faison titled <em>Moose foraging in the temperate forests of Massachusetts: a natural re-wilding experiment</em>. The sites of collection were 156 sites across 2 large, forested watersheds in Central Massachusetts. Data was collected in 2005, but published in 2023. This data was collected to study how moose interact with temperate forests, as they are becoming abundant in these areas again recently. The researchers wanted to study the impact of moose herbivory on vegetation, and what habitat features determine moose winter foraging activity.</p>
<p>The original data was compiled in two csv files. The first contained data related to the plots that were surveyed. This file had 156 rows and 21 variables (including the plot number). The second had data related to the trees in those plots. This dataset had 3,913 rows with 7 variables.</p>
<p>To prepare the data for analysis, I fixed data types in order to work with them best, and checked for any outliers, ultimately deciding to leave them in the data. I saved the updated dataset for Plot as <code>Updated_Moose_Plot_Data.csv</code>.</p>
<p>Additionally, I checked over and edited the levels of the species variable in the tree dataset for spelling errors in the names. I combined the binary columns browsed, stripped, and broken into one new binary interaction column that generalized whether the tree had been interacted with by a moose. This code was done in the file <code>PrepLogisticRegDataset_Dec18.qmd</code>, located in the drafts folder. I saved the new dataset as <code>FinalUpdated_Moose_Tree_Data.csv</code>.</p>
</section>
<section id="multiple-regression" class="level1">
<h1>Multiple Regression</h1>
<p>In this document I will go through the workflow of conducting a mutliple regression statistical analysis on the data from the file Updated_Moose_Plot_Data.csv</p>
<section id="set-up" class="level2">
<h2 class="anchored" data-anchor-id="set-up">Set up</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/ebar/Library/CloudStorage/OneDrive-St.LawrenceUniversity/Classes/Biostats/Biostats F24/Student Work/R Projects/CapDAP/Anderson-Capstone-Project</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co">#for testing significance of correlations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'

The following objects are masked from 'package:dplyr':

    src, summarize

The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally) <span class="co">#for making pairwise plots of variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot) <span class="co">#for looking at correlation matrices</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot) <span class="co">#for plotting correlation matrices</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Read in Data</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Plot <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Updated_Moose_Plot_Data.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Get just the complete cases</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>Plot <span class="ot">&lt;-</span> Plot[<span class="fu">complete.cases</span>(Plot), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Takes it from 156 rows to 70 rows with 22 total variables.</p>
<p><strong>Fix data types</strong></p>
<p>Fix watershed to be a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Plot<span class="sc">$</span>watershed <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Plot<span class="sc">$</span>watershed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p><em>I will use an exploratory approach to determine which predictor variable is the best predictor of moose browse index.</em></p>
<p><u>Null Hypothesis:</u> None of the variables will be predictor of browse index.</p>
<p><u>Alternative Hypothesis:</u> One of more of the variables will be predictors of browse_index. These variables may be distance to water (dist_h2o_m), elevation (elev_m), harvest intensity (harvest_intensity_m2.ha), wetland forest (wetland_forest), or distance to development (dist_dev_m).</p>
<p><u>Biological Justification:</u> Moose eat aquatic plants and are good swimmers, often going in water to cool down (USDA Forest Service, n.d.). They might choose to be closer to water, or in a forest with wetlands. They are adapted to colder temperatures, so they might choose higher elevations where the temperature is naturally cooler (USDA Forest Service, n.d.). Moose are solitary animals, and it’s rare to see one (Massachusetts Division of Fisheries &amp; Wildlife, n.d.). This might be because they choose habitat at farther distances from development. Additionally, moose make trade offs when choosing whether to inhabit old growth or new growth forests. Old growth provides shelter, but new growth provides food, which may be more important (USDA Forest Service, n.d.). Harvested forests have more new growth (Massachusetts Division of Fisheries &amp; Wildlife, n.d.).</p>
<p><em>See sources at the end of this test.</em></p>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p><strong>Response variable:</strong></p>
<ul>
<li>browse_index – Ratio data</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Predictor Variables</th>
<th>Data Types</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>lat</td>
<td>Interval</td>
</tr>
<tr class="even">
<td>elev_m</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>dist_h2o_m</td>
<td>Ratio</td>
</tr>
<tr class="even">
<td>hilltop</td>
<td>Binary</td>
</tr>
<tr class="odd">
<td>swamp</td>
<td>Binary</td>
</tr>
<tr class="even">
<td>wetland_forest</td>
<td>Binary</td>
</tr>
<tr class="odd">
<td>tall_shrubs</td>
<td>Ratio</td>
</tr>
<tr class="even">
<td>dist_conifer_m</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>sugar_maple_ba</td>
<td>Ratio</td>
</tr>
<tr class="even">
<td>red_maple_ba</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>spruce_fir_ba</td>
<td>Ratio</td>
</tr>
<tr class="even">
<td>oak_ba</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>white_pine_ba</td>
<td>Ratio</td>
</tr>
<tr class="even">
<td>harvest_intensity_m2.ha</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>watershed</td>
<td>Nominal</td>
</tr>
<tr class="even">
<td>deer_density</td>
<td>Ratio</td>
</tr>
<tr class="odd">
<td>harvest</td>
<td>Binary</td>
</tr>
<tr class="even">
<td>dist_dev_m</td>
<td>Ratio</td>
</tr>
</tbody>
</table>
</section>
<section id="correlations-plots-guessing-relationships" class="level2">
<h2 class="anchored" data-anchor-id="correlations-plots-guessing-relationships">Correlations, Plots, Guessing relationships</h2>
<section id="first-plot-the-response-variable" class="level3">
<h3 class="anchored" data-anchor-id="first-plot-the-response-variable">First plot the response variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Plot, <span class="fu">aes</span>(browse_index))<span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows that this data set is very 0 heavy, with 25 out of the 70 rows having 0 for the browse_index.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(Plot<span class="sc">$</span>browse_index, <span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   0.0000 143.1818</code></pre>
</div>
</div>
<p>Browse_index ranges from 0 to 143.</p>
</section>
<section id="correlations" class="level3">
<h3 class="anchored" data-anchor-id="correlations">Correlations</h3>
<p>Test if any of the predictor variables are highly correlated, as we wouldn’t want to use both. Variables that have correlation coefficients &gt; +/- 0.7 are considered too highly correlated.</p>
<p>First need to move watershed to the far left because it is categorical so I can get correlation info for the rest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Plot <span class="ot">&lt;-</span> Plot <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(watershed, <span class="at">.after =</span> browse_index)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now run the correlation test</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cor_tests <span class="ot">&lt;-</span> <span class="fu">cor</span>(Plot[,<span class="dv">5</span><span class="sc">:</span><span class="dv">22</span>], <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cor_tests <span class="ot">&lt;-</span> <span class="fu">round</span>(cor_tests, <span class="dv">2</span>) <span class="co">#round for easier viewing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now see which correlation results are statistically significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>cor_tests_results <span class="ot">&lt;-</span> <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(Plot[,<span class="dv">5</span><span class="sc">:</span><span class="dv">22</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Flatten to make it easier to understand the results. (function copied directly from the CapDAP example)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>flattenCorrMatrix<span class="ot">&lt;-</span><span class="cf">function</span>(cormat,pmat){</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  ut<span class="ot">&lt;-</span><span class="fu">upper.tri</span>(cormat)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">row =</span> <span class="fu">rownames</span> (cormat)[<span class="fu">row</span>(cormat) [ut]],</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">column =</span> <span class="fu">rownames</span>(cormat)[<span class="fu">col</span>(cormat)[ut]],</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">cor =</span> (cormat)[ut],</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> pmat[ut]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Plots_table <span class="ot">&lt;-</span> <span class="fu">flattenCorrMatrix</span>(cor_tests_results<span class="sc">$</span>r, cor_tests_results<span class="sc">$</span>P)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Filter for the pairwise correlations with correlation coefficients that are &gt;= to 0.7 or -0.7.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>highly_correlated <span class="ot">&lt;-</span> Plots_table <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cor <span class="sc">&gt;=</span> <span class="fl">0.7</span> <span class="sc">|</span> cor <span class="sc">&lt;=</span> <span class="sc">-</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Went from 153 rows to 7 that are significantly highly correlated.</p>
<p>Harvest intensity and harvest are highly correlated so I’ll just use harvest intensity.</p>
<p>Swamp, wetland forest, tall shrubs, and spruce fir basal area were all highly correlated with each other, so I will just use tall shrubs because it has the most non-zero values.</p>
<p>Here’s a visualization of the correlations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_tests_results<span class="sc">$</span>r, <span class="at">hc.order =</span> <span class="cn">TRUE</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">lab =</span> T, <span class="at">outline.col =</span> <span class="st">"white"</span>, <span class="at">p.mat =</span> cor_tests_results<span class="sc">$</span>P, <span class="at">insig =</span> <span class="st">"blank"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now drop the variables that are too highly correlated (harvest, swamp, wetland_forest, spruce_fir_ba). Also going to drop watershed because it’s all Quabbin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Plot <span class="ot">&lt;-</span> Plot[ <span class="sc">-</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">16</span>,<span class="dv">21</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now there are 70 observations and 14 predictor variables.</p>
<p>Create a new csv to use for the models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Plot, <span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"multregression_cleaned.csv"</span>), <span class="at">row.names =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="guesstimate-predictors-using-correlation" class="level3">
<h3 class="anchored" data-anchor-id="guesstimate-predictors-using-correlation">Guesstimate predictors using correlation</h3>
<p>Look at how highly correlated the response variable is with the predictors to guess which predictors will be best in the multiple regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>predictor_cors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cor</span>(Plot[,<span class="dv">4</span><span class="sc">:</span><span class="dv">17</span>], Plot<span class="sc">$</span>browse_index))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>predictor_cors <span class="ot">&lt;-</span> predictor_cors <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">correlation =</span> cor.Plot...<span class="dv">4</span>.<span class="dv">17</span>...Plot.browse_index.)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>predictor_cors <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(correlation)) <span class="sc">%&gt;%</span> <span class="fu">View</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The highest correlated predictors will the most positive and the most negative correlations.</p>
<p>In this case, it’s harvest intensity (at 0.5370188) and elevation (at 0.4170336) on the positive side. On the negative side it’s oak basal area (at -0.1197530) and deer density (at -0.07061546).</p>
</section>
<section id="plots-with-individual-predictors" class="level3">
<h3 class="anchored" data-anchor-id="plots-with-individual-predictors">Plots with individual predictors</h3>
<p>I will plot the 4 predictors that have the highest correlation with the response variable, browse index.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Plot, <span class="fu">aes</span>(<span class="at">x=</span>harvest_intensity_m2.ha, <span class="at">y=</span>browse_index))<span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Harvest Intensity (m^2/ha)"</span>)<span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Browse index"</span>)<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot makes sense as moose make trade offs when choosing whether to be in old growth or new growth forests. Old growth forests are best for shelter, while new growth forests are best for food, with plenty of young growth (U.S. Forest Service).</p>
<p>This plot has a lot of 0 values for harvest intensity, however.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Plot, <span class="fu">aes</span>(<span class="at">x=</span>elev_m, <span class="at">y=</span>browse_index))<span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Elevation (m)"</span>)<span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Browse index"</span>)<span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the relationship between elevation and browse index. There seems like there could be a slightly sloped line applied, with a general trend of higher browse index and higher elevations. This would make sense as moose prefer cooler temperatures (National Wildlife Federation) that may be found at higher elevations.</p>
<p>This plot has much less 0 values for elevation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Plot, <span class="fu">aes</span>(<span class="at">x=</span>oak_ba, <span class="at">y=</span>browse_index))<span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Relative % of basal oak area in plot"</span>)<span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Browse index"</span>)<span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Oaks are listed as a tree species that moose prefer, so this makes sense as a potential good predictor (Massachusetts Division of Fisheries and Wildlife).</p>
<p>There are a good amount of zero values for relative % of basal oak area though.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Plot, <span class="fu">aes</span>(<span class="at">x=</span>deer_density, <span class="at">y=</span>browse_index))<span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Deer density"</span>)<span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Browse index"</span>)<span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Deer and moose do eat similar foods, so they could be competitors which might influence browse index. However, there doesn’t seem to be major trend here.</p>
</section>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="create-model" class="level2">
<h2 class="anchored" data-anchor-id="create-model">Create Model</h2>
<p>First need to load some more packages to use, clear the environment, and load the cleaned for multiple regression data file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#for checking model performance</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) <span class="co">#for tidying regression output</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps) <span class="co">#allows best subsets linear regression</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co">#for stepAIC function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table) <span class="co">#for confidence intervals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'data.table'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:lubridate':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    between, first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    transpose</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Plot <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"multregression_cleaned.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="best-subsets-regressions" class="level3">
<h3 class="anchored" data-anchor-id="best-subsets-regressions">Best subsets regressions</h3>
<p>Next, build a best subsets regression to look at all the possible models and determine which is best.</p>
<p>Make a matrix with the response variable and predictor variables only. Means I need to drop the plot number variable, and the X variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> Plot <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>(plot), <span class="sc">-</span>(X))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Build the models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>all_subsets.mods <span class="ot">&lt;-</span><span class="fu">regsubsets</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  preds<span class="sc">$</span>browse_index <span class="sc">~</span> ., <span class="co">#specifies the model and . tells it to use all predictors</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> preds,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nbest =</span> <span class="dv">1</span> <span class="co">#tells it to pick the one best model for each number of predictors</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>all_subsets.mods</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(preds$browse_index ~ ., data = preds, nbest = 1)
14 Variables  (and intercept)
                        Forced in Forced out
lat                         FALSE      FALSE
elev_m                      FALSE      FALSE
dist_h2o_m                  FALSE      FALSE
hilltop                     FALSE      FALSE
tall_shrubs                 FALSE      FALSE
dist_conifer_m              FALSE      FALSE
hemlock_ba                  FALSE      FALSE
sugar_maple_ba              FALSE      FALSE
red_maple_ba                FALSE      FALSE
oak_ba                      FALSE      FALSE
white_pine_ba               FALSE      FALSE
harvest_intensity_m2.ha     FALSE      FALSE
deer_density                FALSE      FALSE
dist_dev_m                  FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>all_summary <span class="ot">&lt;-</span><span class="fu">summary</span>(all_subsets.mods)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>outmat<span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(all_summary<span class="sc">$</span>outmat)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>all_summary<span class="sc">$</span>adjr2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2779243 0.3743860 0.3767929 0.3819929 0.3798316 0.3760286 0.3711204
[8] 0.3639645</code></pre>
</div>
</div>
<p>The model with 4 predictors has the highest adjusted R2 value.</p>
<section id="plots-to-view-model-results" class="level4">
<h4 class="anchored" data-anchor-id="plots-to-view-model-results">Plots to view model results</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(all_subsets.mods, <span class="at">scale =</span> <span class="st">"r2"</span>) <span class="co">#plots the R^2 value for each variable across all models</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another plot, with Mallow’s Cp</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plotting with base R</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(all_summary<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(all_subsets.mods, <span class="at">scale =</span> <span class="st">"Cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now a plot of BIC</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(all_summary<span class="sc">$</span>bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(all_subsets.mods, <span class="at">scale =</span> <span class="st">"bic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From these plots, it seems that the best model is the one with 2 predictors in it. The predictors in a 2 predictor model are elevation (elev_m) and harvest intensity (harvest_intensity_m2.ha).</p>
</section>
</section>
<section id="stepwise-regression" class="level3">
<h3 class="anchored" data-anchor-id="stepwise-regression">Stepwise Regression</h3>
<p>Start by defining the intercept-only model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>m.intercept_only <span class="ot">&lt;-</span> <span class="fu">glm</span>(preds<span class="sc">$</span>browse_index <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> preds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next define the model with all predictors</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>m.all.preds <span class="ot">&lt;-</span> <span class="fu">glm</span>(preds<span class="sc">$</span>browse_index <span class="sc">~</span> ., <span class="at">data =</span> preds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now perform the stepwise regression to move through.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>m.stepwise <span class="ot">&lt;-</span> <span class="fu">step</span>(m.intercept_only, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">scope =</span> <span class="fu">formula</span>(m.all.preds))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=689.93
preds$browse_index ~ 1

                          Df Deviance    AIC
+ harvest_intensity_m2.ha  1    52541 668.11
+ elev_m                   1    60993 678.55
&lt;none&gt;                          73834 689.93
+ oak_ba                   1    72775 690.92
+ white_pine_ba            1    73145 691.27
+ hilltop                  1    73243 691.36
+ sugar_maple_ba           1    73307 691.43
+ deer_density             1    73466 691.58
+ lat                      1    73488 691.60
+ dist_conifer_m           1    73594 691.70
+ red_maple_ba             1    73689 691.79
+ tall_shrubs              1    73703 691.80
+ dist_dev_m               1    73775 691.87
+ dist_h2o_m               1    73798 691.89
+ hemlock_ba               1    73834 691.93

Step:  AIC=668.11
preds$browse_index ~ harvest_intensity_m2.ha

                          Df Deviance    AIC
+ elev_m                   1    44853 659.04
+ hilltop                  1    49700 666.22
&lt;none&gt;                          52541 668.11
+ deer_density             1    51971 669.35
+ sugar_maple_ba           1    52065 669.47
+ lat                      1    52225 669.69
+ hemlock_ba               1    52356 669.86
+ tall_shrubs              1    52511 670.07
+ red_maple_ba             1    52531 670.10
+ white_pine_ba            1    52535 670.10
+ dist_dev_m               1    52535 670.10
+ dist_h2o_m               1    52536 670.10
+ dist_conifer_m           1    52541 670.11
+ oak_ba                   1    52541 670.11
- harvest_intensity_m2.ha  1    73834 689.93

Step:  AIC=659.04
preds$browse_index ~ harvest_intensity_m2.ha + elev_m

                          Df Deviance    AIC
&lt;none&gt;                          44853 659.04
+ dist_h2o_m               1    44013 659.71
+ hilltop                  1    44226 660.05
+ lat                      1    44227 660.05
+ tall_shrubs              1    44461 660.42
+ hemlock_ba               1    44524 660.52
+ dist_conifer_m           1    44539 660.55
+ sugar_maple_ba           1    44782 660.93
+ oak_ba                   1    44814 660.98
+ deer_density             1    44815 660.98
+ white_pine_ba            1    44849 661.03
+ red_maple_ba             1    44851 661.03
+ dist_dev_m               1    44852 661.04
- elev_m                   1    52541 668.11
- harvest_intensity_m2.ha  1    60993 678.55</code></pre>
</div>
</div>
<p>This method returned the same 2 predictors in the model, harvest intensity and elevation.</p>
<section id="stepwise-with-the-stepaic-function." class="level4">
<h4 class="anchored" data-anchor-id="stepwise-with-the-stepaic-function.">Stepwise with the stepAIC function.</h4>
<p>Build the full model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">glm</span>(browse_index<span class="sc">~</span> ., <span class="at">family =</span> gaussian, <span class="at">data =</span> preds)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = browse_index ~ ., family = gaussian, data = preds)

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -2.566e+03  3.202e+03  -0.801  0.42631    
lat                      5.343e-04  6.793e-04   0.787  0.43495    
elev_m                   2.740e-01  9.325e-02   2.938  0.00482 ** 
dist_h2o_m              -2.950e-02  2.395e-02  -1.232  0.22325    
hilltop                  1.173e+01  1.388e+01   0.845  0.40191    
tall_shrubs              2.306e-01  3.687e-01   0.625  0.53424    
dist_conifer_m          -1.895e-03  1.616e-02  -0.117  0.90708    
hemlock_ba               2.084e-01  2.111e-01   0.987  0.32777    
sugar_maple_ba           1.099e-01  1.837e-01   0.598  0.55199    
red_maple_ba             1.526e-01  1.969e-01   0.775  0.44175    
oak_ba                   7.288e-02  1.685e-01   0.433  0.66703    
white_pine_ba            7.414e-03  1.926e-01   0.038  0.96944    
harvest_intensity_m2.ha  3.248e-01  7.705e-02   4.215 9.36e-05 ***
deer_density             4.693e-01  2.827e+00   0.166  0.86874    
dist_dev_m               9.533e-04  1.309e-02   0.073  0.94222    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 748.4688)

    Null deviance: 73834  on 69  degrees of freedom
Residual deviance: 41166  on 55  degrees of freedom
AIC: 677.03

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>Harvest intensity and elevation were most significant in this model.</p>
<p>Now begin the stepwise procedure:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>step <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(full, <span class="at">trace =</span> F)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>step<span class="sc">$</span>anova</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stepwise Model Path 
Analysis of Deviance Table

Initial Model:
browse_index ~ lat + elev_m + dist_h2o_m + hilltop + tall_shrubs + 
    dist_conifer_m + hemlock_ba + sugar_maple_ba + red_maple_ba + 
    oak_ba + white_pine_ba + harvest_intensity_m2.ha + deer_density + 
    dist_dev_m

Final Model:
browse_index ~ elev_m + harvest_intensity_m2.ha

               Step Df    Deviance Resid. Df Resid. Dev      AIC
1                                         55   41165.79 677.0321
2   - white_pine_ba  1    1.108847        56   41166.89 675.0340
3      - dist_dev_m  1    4.857348        57   41171.75 673.0423
4  - dist_conifer_m  1    9.845420        58   41181.60 671.0590
5    - deer_density  1   13.890855        59   41195.49 669.0826
6          - oak_ba  1  133.489837        60   41328.98 667.3091
7  - sugar_maple_ba  1  187.354872        61   41516.33 665.6257
8     - tall_shrubs  1  205.848317        62   41722.18 663.9719
9    - red_maple_ba  1  342.057838        63   42064.24 662.5435
10     - hemlock_ba  1  407.241511        64   42471.48 661.2179
11            - lat  1  513.290305        65   42984.77 660.0588
12        - hilltop  1 1028.546101        66   44013.32 659.7141
13     - dist_h2o_m  1  839.427443        67   44852.74 659.0365</code></pre>
</div>
</div>
<p>This method also returned harvest intensity and elevation as the best predictors.</p>
<p>Because they are all the same model, don’t need to compare them.</p>
<p>Create the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>final_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(browse_index <span class="sc">~</span> harvest_intensity_m2.ha <span class="sc">+</span> elev_m, <span class="at">data =</span> preds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
</section>
<section id="check-how-final-model-fits-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-how-final-model-fits-assumptions">Check how final model fits assumptions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(final_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The model seems to fit most of the assumptions. There is a dip in the Homogeneity of Variance assumption, and the Posterior Predictive Check doesn’t quite line up perfectly. The rest seem good.</p>
</section>
<section id="run-the-model" class="level2">
<h2 class="anchored" data-anchor-id="run-the-model">Run the model</h2>
<p>The best model, according to all the tests run above, is the model with 2 predictors (harvest intensity and elevation).</p>
<p>Create the final model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>final_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(browse_index <span class="sc">~</span> harvest_intensity_m2.ha <span class="sc">+</span> elev_m, <span class="at">data =</span> preds)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(final_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = browse_index ~ harvest_intensity_m2.ha + elev_m, 
    data = preds)

Residuals:
    Min      1Q  Median      3Q     Max 
-45.287 -15.906  -3.365   8.041  84.114 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -37.19639   15.75950  -2.360  0.02118 *  
harvest_intensity_m2.ha   0.30547    0.06221   4.910 6.14e-06 ***
elev_m                    0.21853    0.06448   3.389  0.00118 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.87 on 67 degrees of freedom
Multiple R-squared:  0.3925,    Adjusted R-squared:  0.3744 
F-statistic: 21.65 on 2 and 67 DF,  p-value: 5.602e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(final_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: browse_index
                        Df Sum Sq Mean Sq F value    Pr(&gt;F)    
harvest_intensity_m2.ha  1  21293 21292.9  31.807 3.708e-07 ***
elev_m                   1   7688  7688.4  11.485  0.001179 ** 
Residuals               67  44853   669.4                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>From the summary, I see that the model is significant (F=21.65 with 2 and 67 df, p=5.602e-08).</p>
<p>Both harvest intensity and elevation are significant at levels between 0.001 and 0, and between 0.01 and 0.001 respectively.</p>
</section>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2"></h2>
</section>
<section id="replot-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="replot-and-interpretation">Replot and Interpretation</h2>
<p>First, tidy up regression results and put into data frames to more easily work with them. This uses the <code>broom</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">tidy</span>(final_mod)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>coefs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                    estimate std.error statistic    p.value
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 (Intercept)              -37.2     15.8        -2.36 0.0212    
2 harvest_intensity_m2.ha    0.305    0.0622      4.91 0.00000614
3 elev_m                     0.219    0.0645      3.39 0.00118   </code></pre>
</div>
</div>
<p>Get the confidence interval:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="fu">confint</span>(final_mod), <span class="at">keep.rownames =</span> <span class="st">'term'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Combine coefs and ci</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cidf <span class="ot">&lt;-</span> <span class="fu">cbind</span>(coefs, ci)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>cidf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     term    estimate   std.error statistic      p.value
1             (Intercept) -37.1963892 15.75949648 -2.360252 2.118190e-02
2 harvest_intensity_m2.ha   0.3054712  0.06221156  4.910200 6.136999e-06
3                  elev_m   0.2185293  0.06448357  3.388914 1.179357e-03
                     term        2.5 %    97.5 %
1             (Intercept) -68.65247587 -5.740303
2 harvest_intensity_m2.ha   0.18129642  0.429646
3                  elev_m   0.08981953  0.347239</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(cidf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "term"      "estimate"  "std.error" "statistic" "p.value"   "term"     
[7] "2.5 %"     "97.5 %"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>cidf <span class="ot">&lt;-</span>cidf[,<span class="sc">-</span><span class="dv">6</span>] <span class="co">#got rid of second term column</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>cidf <span class="ot">&lt;-</span>cidf <span class="sc">%&gt;%</span> <span class="fu">rename</span>(</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"lower"</span> <span class="ot">=</span> <span class="st">"2.5 %"</span>,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"upper"</span> <span class="ot">=</span> <span class="st">"97.5 %"</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>cidf<span class="sc">$</span>term <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(cidf<span class="sc">$</span>term)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now make a plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cidf, <span class="fu">aes</span>(estimate, term))<span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmax =</span> lower, <span class="at">xmin =</span> upper), <span class="at">height =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the confidence intervals for harvest intensity and elevation are slightly above 0 and don’t overlap with 0, making them significant (F=21.65 with 2 and 67 df, p=5.602e-08). This means that when either harvest intensity or elevation increase, there is a very slight but significant increase in browse index.</p>
<p>These results were part of what I expected, considering moose biology. Moose browse index increasing where there’s a higher harvest intensity makes sense because moose prefer fresh growth to eat, which is more abundant in recently harvested areas (Massachusetts Division of Fisheries &amp; Wildlife, n.d.). It is important to keep in mind that too much harvest would counteract the benefits that a moderate amount of harvest has, as there wouldn’t be enough cover or other resources for moose (Johnson et al, 2024). Moose are adapted to colder temperatures, so seeking out higher elevations that likely have cooler temperatures makes sense (USDA Forest Service, n.d.). I was surprised that wetland and water distance did not have an impact, as moose eat wetland plants and spend time in water to cool down (USDA Forest Service, n.d.). However, there was very few non-zero data points for those variables, so perhaps with more sampling in those areas there could be different results.</p>
<section id="citations" class="level3">
<h3 class="anchored" data-anchor-id="citations">Citations</h3>
<p>Johnson, C. J., &amp; Rea, R. V. (2024). Response of moose to forest harvest and management: A literature review. <em>Canadian Journal of Forest Research</em>, <em>54</em>(4), 366–388. <a href="https://doi.org/10.1139/cjfr-2023-0158" class="uri">https://doi.org/10.1139/cjfr-2023-0158</a></p>
<p>Massachusetts Division of Fisheries &amp; Wildlife. (n.d.). Moose in Massachusetts. Retrieved December 17, 2024, from <a href="https://www.mass.gov/doc/living-with-moose-fact-sheet/download" class="uri">https://www.mass.gov/doc/living-with-moose-fact-sheet/download</a></p>
<p>USDA Forest Service. (n.d.). Moose. Retrieved December 17, 2024, from <a href="https://www.fs.usda.gov/detail/npnht/learningcenter/history-culture/?cid=fseprd675553" class="uri">https://www.fs.usda.gov/detail/npnht/learningcenter/history-culture/?cid=fseprd675553</a></p>
</section>
</section>
</section>
<section id="logistic-regression" class="level1">
<h1>Logistic Regression</h1>
<p>In this file I will go through the workflow of running a logistic regression using data from the file: FinalUpdated_Moose_Tree_Data.csv</p>
<section id="set-up-1" class="level2">
<h2 class="anchored" data-anchor-id="set-up-1">Set up</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(oddsratio) <span class="co">#converts log odds to odds ratios</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visreg) <span class="co">#for visualizing regression output</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read in the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>Tree <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"FinalUpdated_Moose_Tree_Data.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fix data types</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>Tree<span class="sc">$</span>species <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Tree<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just want complete cases for the regression</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>Tree <span class="ot">&lt;-</span> Tree[<span class="fu">complete.cases</span>(Tree), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Went from 3913 rows to 3397 rows.</p>
</section>
<section id="variables-1" class="level2">
<h2 class="anchored" data-anchor-id="variables-1">Variables</h2>
<p>Response:</p>
<ul>
<li>Interaction (was the tree browsed, stripped, and/or broken by a moose) — Binary coded as 0(no) and 1(yes)</li>
</ul>
<p>Predictor:</p>
<ul>
<li>dbh_cm (the tree diameter at breast height) — Ratio</li>
</ul>
</section>
<section id="hypotheses-1" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-1">Hypotheses</h2>
<p>Question: Does dbh_cm have an impact on moose interaction?</p>
<p><u>Null Hypothesis:</u> dbh_cm is not a significant predictor of Interaction by moose.</p>
<p><u>Alternative Hypothesis:</u> dbh_cm is a significant predictor of interaction by moose.</p>
<p><u>Biological Justification:</u> According to the Massachusetts Division of Fisheries &amp; Wildlife, moose prefer new growth for food, so a smaller dbh might be a predictor of Interaction.</p>
</section>
<section id="plots" class="level2">
<h2 class="anchored" data-anchor-id="plots">Plots</h2>
<p>Make a new column with interaction coded as yes and no to make the plots look better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>yes <span class="ot">&lt;-</span> <span class="fu">which</span>(Tree<span class="sc">$</span>Interaction <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>no <span class="ot">&lt;-</span> <span class="fu">which</span>(Tree<span class="sc">$</span>Interaction <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>Tree<span class="sc">$</span>InteractionYN <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>Tree<span class="sc">$</span>InteractionYN[yes] <span class="ot">&lt;-</span> <span class="st">"Yes"</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>Tree<span class="sc">$</span>InteractionYN[no] <span class="ot">&lt;-</span> <span class="st">"No"</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>Tree<span class="sc">$</span>InteractionYN <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Tree<span class="sc">$</span>InteractionYN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Look at the response variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tree, <span class="fu">aes</span>(InteractionYN))<span class="sc">+</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat=</span><span class="st">"count"</span>)<span class="sc">+</span> <span class="co">#Allow for the x axis to be categorical, not continuous</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span> <span class="co">#remove gray background</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Interaction"</span>) <span class="co">#change x axis title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_histogram(stat = "count"): Ignoring unknown parameters:
`binwidth`, `bins`, and `pad`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This shows that there were much more trees that were not interacted with, than those that were interacted with.</p>
<p><strong>Interaction and DBH:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tree, <span class="fu">aes</span>(<span class="at">x =</span> dbh_cm, <span class="at">y =</span> InteractionYN))<span class="sc">+</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span> </span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"DBH (cm)"</span>)<span class="sc">+</span> <span class="co">#change x axis title</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Interaction"</span>) <span class="co">#change y axis title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This seems to show that there are more interactions at a smaller DBH, as the yes interaction points are more dense on the left. My guess is that dbh_cm will be a significant predictor or moose interaction.</p>
</section>
<section id="fit-and-run-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fit-and-run-the-model">Fit and run the model</h2>
<p>Use generalized linear model in order to tell R that responses are binary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>dbh.mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(Interaction <span class="sc">~</span> dbh_cm, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Tree) <span class="co">#Fit the model with dbh as a function of interaction using the binomial family and the tree data set. </span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dbh.mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Interaction ~ dbh_cm, family = "binomial", data = Tree)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.218736   0.072767 -16.749  &lt; 2e-16 ***
dbh_cm      -0.032484   0.004594  -7.071 1.54e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2985.4  on 3396  degrees of freedom
Residual deviance: 2926.0  on 3395  degrees of freedom
AIC: 2930

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The coefficients in this output indicate the average change in the odds of interaction occuring with each increase in dbh by 1 unit. This shows that with a 1 unit increase in dbh, the log odds of moose interaction <em>decreases</em> by 0.032484.</p>
<p>Now calculate the odds ratio to see what that means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">or_glm</span>(</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> Tree, </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">model=</span> dbh.mod, </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">incr =</span> <span class="fu">list</span>(<span class="at">dbh_cm =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  predictor oddsratio ci_low (2.5) ci_high (97.5) increment
1    dbh_cm     0.968        0.959          0.977         1</code></pre>
</div>
</div>
<p>This shows that the oddsratio for dbh_cm = 0.968. This means that for every 1 unit of increase in dbh, the odds that a moose will interact with that tree is 0.968, or 0.968 times less likely.</p>
</section>
<section id="replot-and-interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="replot-and-interpretation-1">Replot and Interpretation</h2>
<p>Plot the results of the odds ratio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tree, <span class="fu">aes</span>(dbh_cm, Interaction))<span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now make a plot based on probabilities using the <code>visreg</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visreg</span>(dbh.mod, <span class="st">"dbh_cm"</span>, </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">gg =</span> T, <span class="co">#use ggplot vs. base R</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">scale =</span> <span class="st">"response"</span>)<span class="sc">+</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tree DBH (cm)"</span>,</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Prob. of moose interaction"</span>)<span class="sc">+</span> <span class="co">#Change the axes titles</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Anderson_FinalReport_CapDAP_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These results show that as tree DHB increases by 1, the probability of moose interaction with that tree decreases by 0.968. This is not a large decrease, but is significant (z = -7.071, p = 1.54e-12) based on the generalized linear model run. This result supports my alternative hypothesis, and is supported biologically. Moose prefer new growth trees (Massachusetts Division of Fisheries &amp; Wildlife, n.d.), so they interact more with trees of a smaller dbh when browsing.</p>
<section id="citations-1" class="level3">
<h3 class="anchored" data-anchor-id="citations-1">Citations</h3>
<p>Massachusetts Division of Fisheries &amp; Wildlife. (n.d.). Moose in Massachusetts. Retrieved December 17, 2024, from <a href="https://www.mass.gov/doc/living-with-moose-fact-sheet/download" class="uri">https://www.mass.gov/doc/living-with-moose-fact-sheet/download</a></p>
</section>
</section>
</section>
<section id="challenges" class="level1">
<h1>Challenges</h1>
<p>To complete this project, I had to learn how to run both a multiple linear regression, and a logistic regression using provided examples. The most challenging part of this process was determining the interpretation of the outputs with my own data.</p>
<p>I had initially planned to run a multiple logistic regression, however I encountered a challenge in doing so, and switched to running a simple logistic regression. The species predictor was too large with the many species names, and R tried to run them all separately, best that I can tell. This did not work out. However, the species names were not significant, and only dbh was, so it was an easy shift to running the simple logistic regression.</p>
<p>Another aspect that I had to figure out was how to best create the Interaction column out of the variables browsed, stripped, and broken. This was a multi-step process of learning different methods both online and from Erika. In the end, this was successful and worked out great!</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>